<a href="https://colab.research.google.com/github/LuisPerdomo123/Inteligencia-Computacional/blob/main/Regression_MLP_Caso_Practico_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Keras: Implementando una RNA para regresión

## Conjunto de datos

### Descripción
Este conjunto de datos contiene información recopilada por el Servicio de Censos de los EEUU sobre viviendas en el área de Boston Mass. Se obtuvo del archivo StatLib (http://lib.stat.cmu.edu/datasets/boston), y se ha utilizado en oda la literatura para comparar diferentes algotritmos de Machine Learning.

Los datos fueron publicados originalmente por Harrison, D y Rubinfeld, D. L. Precios hedónicos y la demanda de aire limpio, J. Environ. Economics & Management, vol 5, 1978.


### Características del conjunto de datos
El conjunto de datos es pequeño, con solo 506 casos. Contienen 14 caracterísiticas que se describen a continuación:



*   CRIM: per capita crime rate by town.
*   ZN: proportion of residential land zoned for lots over 25.000 sq. ft.
*   INDUS: proportion if non-retail business acres per town.
*   CHAS: Charles River dummy variable (1 if tract bounds river: 0 otherwise)
*   NOX: nitric oxides concentration (parts per 10 million).
*   RM: average number of rooms per dwelling.
*   AGE: proportion of owner-occupied units built prior to 1940.
*   DIS: weighted distances to five Boston employment centres.
*   RAD: index of accessibility to radial highways.
*   TAX: full-vakue property-tax rate per 10.000 dollars.
*   PTRATIO: pupil-teacher ratio by twon.
*   B: 1000(Bk-0.63)2 where Bk is the proportion of blacks by town.
*   LSTAT: % lower status of the popullation.
*   MEDV: Median value of owner occupied homes in  dollars.

**El objetivo de nuestro problema de regresión es utilizar las 13 primeras características para predecir el valor de MEDV (que representa el precio de la vivienda).**

## 0. Imports

In [ ]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [ ]:
from tensorflow import keras

## 1. Definición del conjunto de datos de entrenamiento

### 1.1. Improtando el conjunto de datos

In [7]:
from tensorflow.keras import datasets

In [8]:
boston_housing = datasets.boston_housing

In [9]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [10]:
X_train.shape

(404, 13)

In [11]:
X_test.shape

(102, 13)

In [12]:
boston_housing.load_data()

((array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
          3.96900e+02, 1.87200e+01],
         [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
          3.95380e+02, 3.11000e+00],
         [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
          3.75520e+02, 3.26000e+00],
         ...,
         [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
          3.62250e+02, 7.83000e+00],
         [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
          2.61950e+02, 1.57900e+01],
         [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
          3.76700e+02, 4.38000e+00]]),
  array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
         17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
         32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
         23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
         12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.

In [13]:
y_train.shape

(404,)

### 1.2. Visualizando el conjunto de datos

In [14]:
import pandas as pd
import numpy as np

In [16]:
features = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B",
            "LSTAT", "MEDV"]
df_train = pd.DataFrame(np.column_stack([X_train, y_train]), columns=features)
df_train.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
0  1.23247   0.0   8.14   0.0  0.538  6.142   91.7  3.9769   4.0  307.0   
1  0.02177  82.5   2.03   0.0  0.415  7.610   15.7  6.2700   2.0  348.0   
2  4.89822   0.0  18.10   0.0  0.631  4.970  100.0  1.3325  24.0  666.0   
3  0.03961   0.0   5.19   0.0  0.515  6.037   34.5  5.9853   5.0  224.0   
4  3.69311   0.0  18.10   0.0  0.713  6.376   88.4  2.5671  24.0  666.0   
5  0.28392   0.0   7.38   0.0  0.493  5.708   74.3  4.7211   5.0  287.0   
6  9.18702   0.0  18.10   0.0  0.700  5.536  100.0  1.5804  24.0  666.0   
7  4.09740   0.0  19.58   0.0  0.871  5.468  100.0  1.4118   5.0  403.0   
8  2.15505   0.0  19.58   0.0  0.871  5.628  100.0  1.5166   5.0  403.0   
9  1.62864   0.0  21.89   0.0  0.624  5.019  100.0  1.4394   4.0  437.0   

   PTRATIO       B  LSTAT  MEDV  
0     21.0  396.90  18.72  15.2  
1     14.7  395.38   3.11  42.3  
2     20.2  375.52   3.26  50.0  
3     20.2  396.90   8.01  21.1  
4     20.2  391.43  14.65  17.7  
5     19.6  391.13  11.74  18.5  
6     20.2  396.90  23.60  11.3  
7     14.7  396.90  26.42  15.6  
8     14.7  169.27  16.65  15.6  
9     21.2  396.90  34.41  14.4

### 1.3. División del conjunto de datos
Para la realización de una serie de pruebas adicionales vamos a dividir el conjunto de datos de prueba en dos subconjuntos, el conjunto de validación (X_val) y el conjunto de pruebas (X_test)

In [18]:
from sklearn.model_selection import train_test_split
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5)

In [19]:
X_test.shape

(51, 13)

In [20]:
X_val.shape

(51, 13)

## 2. Definición de la arquitectura de la Red Neuronal Artificial

In [21]:
from tensorflow.keras import models
from tensorflow.keras import layers

Definimos una Red Neuronal Artificial formada por 3 capas:
*   La primera capa estarpa formada por 30 neuronas.
*   La segunda capa estará formada por 10 neuronas
*   La última capa estara formada por 1 neurona

In [22]:
network = models.Sequential()

network.add(layers.Dense(30, activation='relu', input_shape=X_train.shape[1:]))
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(1))

Una vez hemos definido la arquitectura de la Red Neuronal Artificial podemos visualizarla junto con el número total de parámetros utilizando el método summary()

In [23]:
network.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                420       
                                                                 
 dense_1 (Dense)             (None, 10)                310       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 741 (2.89 KB)
Trainable params: 741 (2.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### 2.2. Acceso a los elementos definidos de la RNA

In [24]:
network.layers

En este caso vamos a acceder a los parámetros del modelo que componen las neuronas de la primera hidden layer

In [25]:
hidden1 = network.layers[1]

In [26]:
weights, biases = hidden1.get_weights()

Como puede observarse en la siguientes celdas, Keras automáticamente inicializa el valor de los parámetros de manera aleatoria y los bias term con el valor 0.

In [27]:
weights

array([[-0.08041665,  0.14943534,  0.19039857, -0.2800351 , -0.03443632,
        -0.0474914 ,  0.17926234, -0.180007  ,  0.15637231, -0.370987  ],
       [-0.35494852, -0.30315846, -0.289252  , -0.3690467 , -0.09608161,
        -0.19100153,  0.37645894,  0.14252764,  0.1156382 , -0.18332197],
       [ 0.375687  , -0.19748078,  0.21039468,  0.25184923, -0.28369597,
        -0.11207014,  0.15499324, -0.09755555, -0.21106766,  0.36765045],
       [-0.03402096,  0.10346425, -0.19622757, -0.10115713, -0.16006912,
        -0.06973135,  0.33362043,  0.1012468 ,  0.17921054,  0.07670519],
       [ 0.16752487, -0.10584918, -0.3092379 , -0.00066566, -0.146372  ,
        -0.33751547,  0.04824728,  0.00413373, -0.24436569,  0.10996887],
       [ 0.27071106,  0.12284088, -0.20811585,  0.32205373,  0.05736855,
        -0.04685074,  0.06946784, -0.24621996,  0.04249123,  0.18187022],
       [-0.10013449,  0.00936809,  0.22737056, -0.09664416, -0.22679523,
        -0.2975995 ,  0.18950701,  0.07803884

In [28]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)