<a href="https://colab.research.google.com/github/LuisPerdomo123/Inteligencia-Computacional/blob/main/Tensores_y_operaciones_con_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensores y operaciones con tensores

## Tensores

El **tensor** es el elemento fundamental de Tensorflow. En términos prácticos, un tensor es similar a una ndarray de Numpy, es decir, un array multidimensional. La diferencia principal es que los tensores admiten una gama más amplia de valores, por ejemplo, un únicoescalar (un valor simple como el número 15).

In [1]:
# Importamos tensorflow
import tensorflow as tf

tf.__version__

'2.15.0'

Podemos comenzar definiendo un tensor con Tensorflow mediante el método tf.constant()

In [2]:
# El tensor representa una matriz
tf.constant([[1., 2., 3.],[4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
# El tensor representa un escalar
tf.constant(15)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

Al igual un ndarray de Numpy, un tensor tiene una forma (shape) y un tipo (dtype)

In [4]:
t = tf.constant([[1., 2.],[3., 4.]])
t.shape

TensorShape([2, 2])

In [5]:
t.dtype

tf.float32

## Acceso a los elementos de un Tensor

La manera de indexar los valores de un tensor es igual a la que se utiliza para indexar los elementos de un ndarray de NumPy.

In [7]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [8]:
# Acceso a la segunda fila del tensor
t[1,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [9]:
# Acceso a la primera columna del tensor
t[:,0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 4.], dtype=float32)>

## Operaciones con Tensores

Uno de los aspectos más relevantes de los tensores es que podemos realizar todo tipo de operaciones con ellos.

In [10]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [11]:
# Suma de un tensor y un escalar
print(t)
print(t+10)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)


In [12]:
# Suma de dos tensores
print(t+t)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


In [13]:
# Cuadrado de un tensor
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

Tensorflow nos proporciona una amplia gama de funciones matemáticas que podemos utilizar para operar con tensores:

*   tf.exp()
*   tf.sqrt()
*   tf.transpose()
*   ...



## Tensores y conversión de tipos

Una de las cosas relevantes que se debe tener en cuenta cuando se utiliza Tensorflow, es que no realiza conversión de tipos al realizar una operación. Esto quiere decir que si no se utilizan valores del mismo tipo en la operación, se producirá una excepción.[

In [14]:
# Creación de dos tensores
t1 = tf.constant(1.0)
t2 = tf.constant(2)

In [15]:
print("Tipo t1:", t1.dtype)
print("Tipo t2:", t2.dtype)

Tipo t1: <dtype: 'float32'>
Tipo t2: <dtype: 'int32'>


In [16]:
try:
  t3 = t1+t2
except Exception as e:
  print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [17]:
try:
  tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])
except Exception as e:
  print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 


## Tensores variables

Hasta ahora, la estructuras de Tensorflow que hemos utilizado para almacenar valores son inmutables, esto quiere decur que no podemos realizar modificaciones una vez se han creado.

In [18]:
t = tf.constant([1.0, 2.0, 3.0])
t[0] = 4.0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Si necesitamos crear una estructura que pueda modificarse después de haber sido creada, entonces tenemos que utilizar tf.Variable

In [20]:
t = tf.Variable([1.0,2.0,3.0])
print("Tensor original:", t.value())

t[0].assign(4.0)
print("Tensor modificado:", t.value())

Tensor original: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Tensor modificado: tf.Tensor([4. 2. 3.], shape=(3,), dtype=float32)


Tensorlfow soporta otros tipos de estructuras de datos como las cadenas de texto

In [21]:
tf.constant(b"Hola mundo")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hola mundo'>

In [22]:
tf.constant("españa")

<tf.Tensor: shape=(), dtype=string, numpy=b'espa\xc3\xb1a'>

In [23]:
tf.constant([["hola","mundo","españa"]])

<tf.Tensor: shape=(1, 3), dtype=string, numpy=array([[b'hola', b'mundo', b'espa\xc3\xb1a']], dtype=object)>